### ISSUE TITLE
hasOwnProperty

### ISSUE THREAD

**Issue by benbarefield** [SmartSparrow/checkjs#2]
Hey Ragil,
Found a bug when type checking every element of an array. The code uses a for-in loop, but doesn't use hasOwnProperty, so prototype methods don't get filtered out when trying to iterate across an array. I don't have the ability to push to this repo, how would you like the change?

**Comment by lerice** [comment]
Funny you brought this up Ben - one of our sims came crashing down and much investigation later we have this guy: https://github.com/SmartSparrow/checkjs/pull/3

**Comment by eliasem** [comment]
@benbarefield, Ownership of this project has been given to SPR. Eric has fixed the issue you mentioned above.
